- name: registry_memstats_alloc_bytes
  path: $.memstats.Alloc
- name: registry_memstats_total_alloc_bytes
  path: $.memstats.TotalAlloc
- name: registry_memstats_sys_bytes
  path: $.memstats.Sys
- name: registry_memstats_lookups
  path: $.memstats.Lookups
- name: registry_memstats_mallocs
  path: $.memstats.Mallocs
- name: registry_memstats_frees
  path: $.memstats.Frees
- name: registry_memstats_heap_alloc_bytes
  path: $.memstats.HeapAlloc
- name: registry_memstats_heap_sys_bytes
  path: $.memstats.HeapSys
- name: registry_memstats_heap_idle_bytes
  path: $.memstats.HeapIdle
- name: registry_memstats_heap_in_use_bytes
  path: $.memstats.HeapInuse
- name: registry_memstats_heap_released_bytes
  path: $.memstats.HeapReleased
- name: registry_memstats_heap_heap_objects
  path: $.memstats.HeapObjects
- name: registry_memstats_stack_in_use_bytes
  path: $.memstats.StackInuse
- name: registry_memstats_stack_sys_bytes
  path: $.memstats.StackSys
- name: registry_memstats_m_span_in_use_bytes
  path: $.memstats.MSpanInuse
- name: registry_memstats_m_span_sys_bytes
  path: $.memstats.MSpanSys
- name: registry_memstats_m_cache_in_use_bytes
  path: $.memstats.MCacheInuse
- name: registry_memstats_m_cache_sys_bytes
  path: $.memstats.MCacheSys
- name: registry_memstats_buck_hash_sys_bytes
  path: $.memstats.BuckHashSys
- name: registry_memstats_gc_sys_bytes
  path: $.memstats.GCSys
- name: registry_memstats_other_sys_bytes
  path: $.memstats.OtherSys
- name: registry_memstats_next_gc
  path: $.memstats.NextGC
- name: registry_memstats_last_gc
  path: $.memstats.LastGC
- name: registry_memstats_pause_total_n_s
  path: $.memstats.PauseTotalNs
- name: registry_memstats_num_gc
  path: $.memstats.NumGC
- name: registry_memstats_gc_cpu_fraction
  path: $.memstats.GCCPUFraction

- name: registry_proxy_blobs_requests
  path: $.registry.proxy.blobs.Requests
- name: registry_proxy_blobs_hits
  path: $.registry.proxy.blobs.Hits
- name: registry_proxy_blobs_misses
  path: $.registry.proxy.blobs.Misses
- name: registry_proxy_blobs_pulled_bytes
  path: $.registry.proxy.blobs.BytesPulled
- name: registry_proxy_blobs_pushed_bytes
  path: $.registry.proxy.blobs.BytesPushed

- name: registry_proxy_manifests_requests
  path: $.registry.proxy.manifests.Requests
- name: registry_proxy_manifests_hits
  path: $.registry.proxy.manifests.Hits
- name: registry_proxy_manifests_misses
  path: $.registry.proxy.manifests.Misses
- name: registry_proxy_manifests_pulled_bytes
  path: $.registry.proxy.manifests.BytesPulled
- name: registry_proxy_manifests_pushed_bytes
  path: $.registry.proxy.manifests.BytesPushed